app:
  kafka:
    topic: "metrics-topic"
  metrics:
    - jvm.memory.max
    - disk.free
    - process.uptime
    - application.started.time
spring:
  kafka:
    producer:
      client-id: "metric-producer"
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        transaction-id-prefix: tx.
#     properties:
#        "[spring.json.type.mapping]": foo:com.example.kafkaexample.model.Foo1, bar:com.example.kafkaexample.model.Bar1
server:
  port: 8081

management.endpoints.web.exposure.include: metrics