app:
  kafka:
    topic: "metrics-topic"
  metrics:
    - jvm.memory.max
    - disk.free
    - process.uptime
    - application.started.time

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      client-id: "metric-producer"

server:
  port: 8081

management.endpoints.web.exposure.include: metrics