app:
  kafka:
    topic: "metrics-topic"

spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      client-id: "metric-consumer"
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: "metricsGroup"
